[project]
name = "cholangiohub-processing"
version = "0.1.0"
description = "Bronze -> Silver processing service for CholangioHub"
requires-python = ">=3.13"

dependencies = [
    "cholangiohub-shared",
    "minio>=7.2",
    "pyspark>=3.5",
    "fastapi>=0.95",
    "requests>=2.31",
    "uvicorn[standard]>=0.23"
]

[tool.uv]
package = true
